from pathlib import Path

ROOT = Path.cwd()
cli_path = ROOT / "src" / "upwork_triage" / "cli.py"
prospects_path = ROOT / "src" / "upwork_triage" / "prospects.py"

prospects_code = 'from __future__ import annotations\n\nimport json\nimport sqlite3\nfrom typing import Any, Mapping\n\nPROSPECT_BUCKET_ORDER = ("AI_EVAL", "MANUAL_EXCEPTION", "LOW_PRIORITY_REVIEW")\nDEFAULT_PROSPECT_USER_STATUSES = ("new", "seen", "saved")\nMISSING = "\\N{EM DASH}"\n\n__all__ = ["fetch_enriched_prospects", "render_enriched_prospects"]\n\n\ndef fetch_enriched_prospects(\n    conn: sqlite3.Connection,\n    limit: int | None = None,\n    *,\n    include_statuses: tuple[str, ...] | list[str] | None = None,\n) -> list[dict[str, object]]:\n    statuses = tuple(include_statuses) if include_statuses is not None else DEFAULT_PROSPECT_USER_STATUSES\n    if not statuses:\n        return []\n\n    status_placeholders = ", ".join("?" for _ in statuses)\n    query = f"""\n        SELECT\n            jobs.job_key,\n            jobs.upwork_job_id,\n            jobs.user_status,\n            COALESCE(normalized.source_url, jobs.source_url) AS source_url,\n\n            normalized.j_title,\n            normalized.j_description,\n            normalized.j_mins_since_posted,\n            normalized.j_posted_at,\n            normalized.j_project_type,\n            normalized.j_contract_type,\n            normalized.j_pay_fixed,\n            normalized.j_pay_hourly_low,\n            normalized.j_pay_hourly_high,\n            normalized.j_skills,\n            normalized.j_qualifications,\n            normalized.j_apply_cost_connects,\n\n            normalized.c_verified_payment,\n            normalized.c_verified_phone,\n            normalized.c_country,\n            normalized.c_hist_jobs_posted,\n            normalized.c_hist_jobs_open,\n            normalized.c_hist_hire_rate,\n            normalized.c_hist_total_spent,\n            normalized.c_hist_hires_total,\n            normalized.c_hist_hires_active,\n            normalized.c_hist_avg_hourly_rate,\n            normalized.c_hist_hours_hired,\n            normalized.c_hist_member_since,\n\n            normalized.a_proposals,\n            normalized.a_hires,\n            normalized.a_interviewing,\n            normalized.a_invites_sent,\n            normalized.a_invites_unanswered,\n            normalized.a_mins_since_cli_viewed,\n\n            filter.routing_bucket,\n            filter.score,\n            filter.reject_reasons_json,\n            filter.positive_flags_json,\n            filter.negative_flags_json,\n\n            enrichment.created_at AS manual_enriched_at,\n            enrichment.raw_manual_text,\n            enrichment.parse_status\n        FROM jobs\n        JOIN job_snapshots_normalized AS normalized\n            ON normalized.id = jobs.latest_normalized_snapshot_id\n        JOIN filter_results AS filter\n            ON filter.id = (\n                SELECT latest_filter.id\n                FROM filter_results AS latest_filter\n                WHERE latest_filter.job_snapshot_id = normalized.id\n                ORDER BY latest_filter.id DESC\n                LIMIT 1\n            )\n        JOIN manual_job_enrichments AS enrichment\n            ON enrichment.job_key = jobs.job_key\n            AND enrichment.is_latest = 1\n        WHERE\n            jobs.latest_normalized_snapshot_id IS NOT NULL\n            AND jobs.user_status IN ({status_placeholders})\n            AND filter.routing_bucket != \'DISCARD\'\n        """\n\n    cursor = conn.execute(query, statuses)\n    rows = [\n        _decode_row(_row_to_dict(row, cursor.description))\n        for row in cursor.fetchall()\n    ]\n    rows.sort(key=_prospect_sort_key)\n    if limit is not None:\n        return rows[:limit]\n    return rows\n\n\ndef render_enriched_prospects(rows: list[Mapping[str, object]]) -> str:\n    if not rows:\n        return "No enriched prospects found."\n\n    lines: list[str] = [\n        "ENRICHED PROSPECTS",\n        "",\n        "Use this dump for manual review or paste it into ChatGPT/external AI.",\n        "No internal AI verdict has been generated by Automat.",\n        "",\n    ]\n\n    for index, row in enumerate(rows, start=1):\n        lines.extend(_render_prospect(index, row))\n        lines.append("")\n\n    return "\\n".join(lines).rstrip()\n\n\ndef _render_prospect(index: int, row: Mapping[str, object]) -> list[str]:\n    title = _string_value(row.get("j_title"))\n    job_key = _string_value(row.get("job_key"))\n    upwork_job_id = _string_value(row.get("upwork_job_id"))\n    user_status = _string_value(row.get("user_status"))\n    source_url = _string_value(row.get("source_url"))\n\n    bucket = _string_value(row.get("routing_bucket"))\n    score = _format_score(row.get("score"))\n    positive_flags = _format_string_list(row.get("positive_flags"))\n    negative_flags = _format_string_list(row.get("negative_flags"))\n    reject_reasons = _format_string_list(row.get("reject_reasons"))\n\n    contract_type = _string_value(row.get("j_contract_type"))\n    pay = _format_pay_summary(row)\n    posted_age = _format_minutes(row.get("j_mins_since_posted"))\n    posted_at = _string_value(row.get("j_posted_at"))\n    skills = _string_value(row.get("j_skills"))\n    qualifications = _string_value(row.get("j_qualifications"))\n    description = _string_value(row.get("j_description"))\n\n    verified_payment = _format_bool_yes_no(row.get("c_verified_payment"))\n    verified_phone = _format_bool_yes_no(row.get("c_verified_phone"))\n    country = _string_value(row.get("c_country"))\n    total_spent = _format_money(row.get("c_hist_total_spent"))\n    total_hires = _string_value(row.get("c_hist_hires_total"))\n    jobs_posted = _string_value(row.get("c_hist_jobs_posted"))\n    hire_rate = _format_percent(row.get("c_hist_hire_rate"))\n    jobs_open = _string_value(row.get("c_hist_jobs_open"))\n    active_hires = _string_value(row.get("c_hist_hires_active"))\n    avg_hourly = _format_money(row.get("c_hist_avg_hourly_rate"))\n    hours_hired = _string_value(row.get("c_hist_hours_hired"))\n    member_since = _string_value(row.get("c_hist_member_since"))\n\n    proposals = _string_value(row.get("a_proposals"))\n    hires = _string_value(row.get("a_hires"))\n    interviewing = _string_value(row.get("a_interviewing"))\n    invites = _string_value(row.get("a_invites_sent"))\n    unanswered_invites = _string_value(row.get("a_invites_unanswered"))\n    last_viewed = _format_minutes(row.get("a_mins_since_cli_viewed"))\n\n    manual_enriched_at = _string_value(row.get("manual_enriched_at"))\n    parse_status = _string_value(row.get("parse_status"))\n    raw_manual_text = _string_value(row.get("raw_manual_text"))\n\n    return [\n        f"--- PROSPECT {index} ---",\n        f"TITLE: {title}",\n        f"URL: {source_url}",\n        f"JOB_KEY: {job_key}",\n        f"UPWORK_ID: {upwork_job_id}",\n        f"USER_STATUS: {user_status}",\n        "",\n        "OFFICIAL FILTER",\n        f"- bucket: {bucket}",\n        f"- score: {score}",\n        f"- positive_flags: {positive_flags}",\n        f"- negative_flags: {negative_flags}",\n        f"- reject_reasons: {reject_reasons}",\n        "",\n        "JOB / SCOPE",\n        f"- contract_type: {contract_type}",\n        f"- pay: {pay}",\n        f"- posted_age: {posted_age}",\n        f"- posted_at: {posted_at}",\n        f"- skills: {skills}",\n        f"- qualifications: {qualifications}",\n        "- description:",\n        _indent_block(description),\n        "",\n        "OFFICIAL CLIENT SIGNALS",\n        f"- payment_verified: {verified_payment}",\n        f"- phone_verified: {verified_phone}",\n        f"- country: {country}",\n        f"- total_spent: {total_spent}",\n        f"- hires_total: {total_hires}",\n        f"- jobs_posted: {jobs_posted}",\n        f"- hire_rate: {hire_rate}",\n        f"- jobs_open: {jobs_open}",\n        f"- active_hires: {active_hires}",\n        f"- avg_hourly_rate: {avg_hourly}",\n        f"- hours_hired: {hours_hired}",\n        f"- member_since: {member_since}",\n        "",\n        "ACTIVITY / COMPETITION",\n        f"- proposals: {proposals}",\n        f"- hires_on_job: {hires}",\n        f"- interviewing: {interviewing}",\n        f"- invites_sent: {invites}",\n        f"- unanswered_invites: {unanswered_invites}",\n        f"- client_last_viewed: {last_viewed}",\n        "",\n        "MANUAL UI TEXT",\n        f"- enriched_at: {manual_enriched_at}",\n        f"- parse_status: {parse_status}",\n        "- raw_manual_text:",\n        _indent_block(raw_manual_text),\n        "",\n        "LOCAL ACTIONS",\n        f"- mark seen: py -m upwork_triage action {job_key} seen",\n        f"- mark skipped: py -m upwork_triage action {job_key} skipped",\n        f"- mark saved: py -m upwork_triage action {job_key} saved",\n    ]\n\n\ndef _decode_row(row: dict[str, object]) -> dict[str, object]:\n    row["positive_flags"] = _parse_json_string_list(row.get("positive_flags_json"))\n    row["negative_flags"] = _parse_json_string_list(row.get("negative_flags_json"))\n    row["reject_reasons"] = _parse_json_string_list(row.get("reject_reasons_json"))\n    row.pop("positive_flags_json", None)\n    row.pop("negative_flags_json", None)\n    row.pop("reject_reasons_json", None)\n    return row\n\n\ndef _parse_json_string_list(value: object | None) -> list[str]:\n    if not isinstance(value, str) or not value.strip():\n        return []\n    try:\n        parsed = json.loads(value)\n    except json.JSONDecodeError:\n        return []\n    if not isinstance(parsed, list):\n        return []\n    return [str(item) for item in parsed if isinstance(item, str)]\n\n\ndef _prospect_sort_key(row: Mapping[str, object]) -> tuple[int, int, float, float]:\n    bucket = str(row.get("routing_bucket") or "")\n    bucket_index = (\n        PROSPECT_BUCKET_ORDER.index(bucket)\n        if bucket in PROSPECT_BUCKET_ORDER\n        else len(PROSPECT_BUCKET_ORDER)\n    )\n    posted_minutes = row.get("j_mins_since_posted")\n    if isinstance(posted_minutes, bool):\n        posted_minutes = None\n    posted_missing = 0 if isinstance(posted_minutes, int | float) else 1\n    posted_value = float(posted_minutes) if isinstance(posted_minutes, int | float) else float("inf")\n    score = row.get("score")\n    score_value = float(score) if isinstance(score, int | float) and not isinstance(score, bool) else float("-inf")\n    return (bucket_index, posted_missing, posted_value, -score_value)\n\n\ndef _format_pay_summary(row: Mapping[str, object]) -> str:\n    contract_type = _string_value(row.get("j_contract_type")).lower()\n    fixed_pay = row.get("j_pay_fixed")\n    hourly_low = row.get("j_pay_hourly_low")\n    hourly_high = row.get("j_pay_hourly_high")\n\n    if contract_type == "fixed":\n        return f"fixed {_format_money(fixed_pay)}"\n    if contract_type == "hourly":\n        low = _format_money(hourly_low)\n        high = _format_money(hourly_high)\n        if low == MISSING and high == MISSING:\n            return "hourly " + MISSING\n        return f"hourly {low}-{high}"\n    return MISSING\n\n\ndef _format_bool_yes_no(value: object | None) -> str:\n    if value is None:\n        return MISSING\n    if value in {1, True}:\n        return "yes"\n    if value in {0, False}:\n        return "no"\n    return _string_value(value)\n\n\ndef _format_money(value: object | None) -> str:\n    if value is None or isinstance(value, bool):\n        return MISSING\n    if isinstance(value, int | float):\n        return f"${float(value):,.2f}"\n    return _string_value(value)\n\n\ndef _format_percent(value: object | None) -> str:\n    if value is None or isinstance(value, bool):\n        return MISSING\n    if isinstance(value, int | float):\n        return f"{float(value):.1f}%"\n    return _string_value(value)\n\n\ndef _format_score(value: object | None) -> str:\n    if value is None or isinstance(value, bool):\n        return MISSING\n    if isinstance(value, int | float):\n        if float(value).is_integer():\n            return str(int(float(value)))\n        return f"{float(value):.1f}"\n    return _string_value(value)\n\n\ndef _format_minutes(value: object | None) -> str:\n    if value is None or isinstance(value, bool):\n        return MISSING\n    if isinstance(value, int | float):\n        return f"{int(value)}m"\n    return _string_value(value)\n\n\ndef _format_string_list(value: object | None) -> str:\n    if isinstance(value, list):\n        text_items = [str(item).strip() for item in value if str(item).strip()]\n        if text_items:\n            return ", ".join(text_items)\n        return "none"\n    if value is None:\n        return "none"\n    return _string_value(value)\n\n\ndef _string_value(value: object | None) -> str:\n    if value is None:\n        return MISSING\n    text = str(value).strip()\n    return text if text else MISSING\n\n\ndef _indent_block(text: str) -> str:\n    if text == MISSING:\n        return "  " + MISSING\n    return "\\n".join(f"  {line}" if line else "" for line in text.splitlines())\n\n\ndef _row_to_dict(row: Any, description: Any | None = None) -> dict[str, object]:\n    if isinstance(row, sqlite3.Row):\n        return {key: row[key] for key in row.keys()}\n    if hasattr(row, "keys"):\n        return {key: row[key] for key in row.keys()}\n    if description is None:\n        raise TypeError("expected row-like object with keys() or cursor metadata")\n    column_names = [column[0] for column in description]\n    return dict(zip(column_names, row, strict=True))\n'

if not cli_path.exists():
    raise SystemExit(f"Missing {cli_path}. Run this script from the repo root.")

prospects_path.write_text(prospects_code, encoding="utf-8")
print(f"Wrote {prospects_path}")

cli = cli_path.read_text(encoding="utf-8")

manual_import_block = """from upwork_triage.manual_enrichment import (
    export_enrichment_csv,
    import_enrichment_csv,
)
"""
prospects_import_block = """from upwork_triage.manual_enrichment import (
    export_enrichment_csv,
    import_enrichment_csv,
)
from upwork_triage.prospects import (
    fetch_enriched_prospects,
    render_enriched_prospects,
)
"""

if "from upwork_triage.prospects import" not in cli:
    if manual_import_block not in cli:
        raise SystemExit("Could not find manual_enrichment import block in cli.py")
    cli = cli.replace(manual_import_block, prospects_import_block)
    print("Inserted prospects import")
else:
    print("Prospects import already present")

dispatch_anchor = """        if args.command == "import-enrichment-csv":
            return _run_import_enrichment_csv(
                input_path=args.input_path,
                stdout=out,
            )
"""
dispatch_insert = dispatch_anchor + """        if args.command == "dump-prospects":
            return _run_dump_prospects(
                limit=args.limit,
                stdout=out,
            )
"""

if 'args.command == "dump-prospects"' not in cli:
    if dispatch_anchor not in cli:
        raise SystemExit("Could not find import-enrichment-csv dispatch block in cli.py")
    cli = cli.replace(dispatch_anchor, dispatch_insert)
    print("Inserted dump-prospects dispatch")
else:
    print("dump-prospects dispatch already present")

parser_anchor = """    import_enrichment_parser.add_argument(
        "input_path",
        help="Path to the edited enrichment CSV worksheet.",
    )
"""
parser_insert = parser_anchor + """    dump_prospects_parser = subparsers.add_parser(
        "dump-prospects",
        help="Render enriched prospect packets for manual or external-AI review.",
    )
    dump_prospects_parser.add_argument(
        "--limit",
        type=_positive_int_arg,
        help="Maximum number of enriched prospects to render.",
    )
"""

if '"dump-prospects"' not in cli.split("def _run_fake_demo", 1)[0]:
    if parser_anchor not in cli:
        raise SystemExit("Could not find import-enrichment-csv parser block in cli.py")
    cli = cli.replace(parser_anchor, parser_insert)
    print("Inserted dump-prospects parser")
else:
    print("dump-prospects parser already present")

function_anchor = """def _run_upwork_auth_url(*, stdout: TextIO) -> int:
    config = load_config()
    print(build_authorization_url(config), file=stdout)
    return 0
"""
function_insert = """def _run_dump_prospects(*, limit: int | None, stdout: TextIO) -> int:
    config = load_config()
    db_path = Path(config.db_path)
    _ensure_parent_dir(db_path)

    conn = connect_db(db_path)
    try:
        initialize_db(conn)
        rows = fetch_enriched_prospects(conn, limit=limit)
        print(render_enriched_prospects(rows), file=stdout)
    finally:
        conn.close()

    return 0


""" + function_anchor

if "def _run_dump_prospects" not in cli:
    if function_anchor not in cli:
        raise SystemExit("Could not find _run_upwork_auth_url anchor in cli.py")
    cli = cli.replace(function_anchor, function_insert)
    print("Inserted _run_dump_prospects")
else:
    print("_run_dump_prospects already present")

cli_path.write_text(cli, encoding="utf-8")
print(f"Updated {cli_path}")
print("Done. Try: py -m upwork_triage dump-prospects")
